import mongoose from "mongoose";

const GithubRepositorySchema = new mongoose.Schema({
  org: { type: mongoose.Schema.Types.ObjectId, ref: "GithubOrganizations" },
  userId: { type: mongoose.Schema.Types.ObjectId, ref: "User" },
  id: Number,
  name: String,
  full_name: String,
  private: Boolean,
  html_url: String,
  description: String,
  fork: Boolean,
  url: String,
  forks_url: String,
  keys_url: String,
  collaborators_url: String,
  teams_url: String,
  hooks_url: String,
  issue_events_url: String,
  events_url: String,
  assignees_url: String,
  branches_url: String,
  tags_url: String,
  blobs_url: String,
  git_tags_url: String,
  git_refs_url: String,
  trees_url: String,
  contributors_url: String,
  commits_url: String,
  visibility: String,
  archived: Boolean,
  forks: Number,
  open_issues: Number,
  watchers: Number,
  default_branch: String,
  ssh_url: String,
  clone_url: String,
  svn_url: String,
  git_url: String,
  license: {
    key: String,
    name: String,
    url: String,
    spdx_id: String,
  },
  created_at: Date,
  updated_at: Date,
});

export default mongoose.model("GithubRepository", GithubRepositorySchema);
